### ISSUE TITLE
ava.lang.IllegalArgumentException; View not attached to window manager 

### ISSUE THREAD

**Issue by aburasel** [abdullahalshafi/BasicLocationPicker#1]
**_This is a crash caused by your app dismissing a dialog attached to an Activity which is finishing or finished. This can happen in a number of ways -- for example, if an AsyncTask is running while a ProgressDialog is showing, and the user rotates the device, causing the Activity to be recreated._** 

Fatal Exception: java.lang.IllegalArgumentException: View=DecorView@1b0fa70[LocationHelperActivity] not attached to window manager
       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:550)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:454)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:141)
       at android.app.Dialog.dismissDialog(Dialog.java:420)
       at android.app.Dialog.dismiss(Dialog.java:402)
       at `com.shafi.basic_location_picker.BasicLocationPickerProgressDialogWithMessage.dismiss(BasicLocationPickerProgressDialogWithMessage.kt:43)`
       at com.shafi.basic_location_picker.LocationFinder.dismissProgressDialog(LocationFinder.kt:54)
       at com.shafi.basic_location_picker.LocationFinder.getLocation$lambda-1$lambda-0(LocationFinder.kt:69)
       at com.shafi.basic_location_picker.LocationFinder.$r8$lambda$2sF7fUj-x2gom37TXWMIG_lMKsY()
       at com.shafi.basic_location_picker.LocationFinder$$ExternalSyntheticLambda1.run(:4)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:257)
       at android.app.ActivityThread.main(ActivityThread.java:8218)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1016)

**Comment by abdullahalshafi** [comment]
Fixed in the new release
